### ISSUE TITLE
Error: Uncaught TypeError: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by NovaMoon** [moebooru/moebooru#53]
when i try to batch upload something i get this error in the "user_errors.log"

`Error: Uncaught TypeError: Cannot read property 'text' of null
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
URL: https://<website>/
Cookies: wp-settings-1=libraryContent=browse; wp-settings-time-1=1468717497; firstVisit=1468723681719; vote=1; hide-news-ticker=20130822; login=NovaMoon; show_defaults_to_edit=1; mode=view; tag-script=; __utma=240815900.91403891.1468985611.1469975383.1469999523.17; __utmz=240815900.1468985611.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); forum_post_last_read_at="2016-07-19T05:13:10.602Z"; country=DE; user_id=1; user_info=1;50;0; has_mail=0; comments_updated=0; mod_pending=0; block_reason=; resize_image=0; show_advanced_editing=0; my_tags=; held_post_count=0; reported_error=1
File: https://<website>/assets/application-7b4990ee69ade56f45feb7871fa4226804d28627e47caa1cbc3b5ef081cf950e.js line 6`

**Comment by nanaya** [comment]
Fixed.

**Comment by NovaMoon** [comment]
Problem persists with different error

Error: Uncaught TypeError: Cannot read property 'value' of undefined

**Comment by nanaya** [comment]
That'd be a different bug.

**Comment by NovaMoon** [comment]
File: https://<website>/assets/moe-legacy/application-3a4cd5a74b2c27bc0eb8607f13f0849e50353e03eccc0ec4ac8acb542c308ab7.js line 11

**Comment by nanaya** [comment]
That doesn't help. At least which page causes the error is needed.

**Comment by NovaMoon** [comment]
ok here is the full error log.

> Error: Uncaught TypeError: Cannot read property 'value' of undefined
UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36
URL: https://website/batch/create?url=https%3A%2F%2Fimgur.com%2Fa%2Fanjym%2338&commit=Load+file+index
File: https://website/assets/moe-legacy/application-3a4cd5a74b2c27bc0eb8607f13f0849e50353e03eccc0ec4ac8acb542c308ab7.js line 11

**Comment by nanaya** [comment]
I can't reproduce the error. I can guess what it is but without precise location of the error it'll take a long time for me to fix (and I don't quite have time for that).

Post the full stack trace in chrome. Or even better run in development mode so I can see which file is causing the error.

**Comment by NovaMoon** [comment]
running in dev. mode. where do i find the error now?

**Comment by nanaya** [comment]
browser console

**Comment by NovaMoon** [comment]
the console shows nothing for me

**Comment by nanaya** [comment]
You to visit the page again and do same action.

**Comment by NovaMoon** [comment]
my bad. had to tick the "preserve log" box :D 

https://i.imgur.com/jo26HuQ.png

**Comment by nanaya** [comment]
Should be fixed in 6e04283.

**Comment by NovaMoon** [comment]
new errors~

https://i.imgur.com/D9DDrsK.png

**Comment by nanaya** [comment]
Try a full reload first.

**Comment by NovaMoon** [comment]
i did. error persists

**Comment by nanaya** [comment]
Fixed in e2ab9a5.

**Comment by NovaMoon** [comment]
next error

https://i.imgur.com/jJgGZHg.png

**Comment by NovaMoon** [comment]
applied your fix. no more error messages but its still not working. 

"Status:pending"

**Comment by nanaya** [comment]
As I said, the error is not related to batch upload.

Check `/job_task`, if it's empty, run `bundle exec rake create_jobs`.

Run `bundle exec rake job:start`.

**Comment by NovaMoon** [comment]
i joined the irc~

i did the commands and the /job_task gives me another error related to the active_support gem

> active_support/dependencies.rb:274:in `require': cannot load such file -- active_record/legacy_yaml_adapter (LoadError)

**Comment by nanaya** [comment]
try `bundle install && gem pristine -a`

**Comment by NovaMoon** [comment]
no more errors. 

`/job_task` shows only that its started. 

stil on pending

**Comment by NovaMoon** [comment]
its looping this entry in the development.log

http://pastebin.com/eRNUxSgw
