### ISSUE TITLE
Image search options broken

### ISSUE THREAD

**Issue by fireattack** [moebooru/moebooru#86]
1. Go https://yande.re/post/similar
2. Put in any URL or local image, and click "search"
3. When the results returns, click any of the option on the left (choose different services, ignore colors etc.)

What happened: it resets the page instead of applying corresponding options.

another way to test: just open https://yande.re/post/similar?services=all and search an image. It still only returns results from Yande.re.

**Comment by fireattack** [comment]
It works fine for on-site image search (such as https://yande.re/post/similar/399750?services=all )

**Comment by nanaya** [comment]
Fixed.

**Comment by fireattack** [comment]
Two problems remain:

1. If you select the options *first*, then upload/submit your image, the option will be reset;
2. Can't use multiple options together. You can if you modify the URL by hand (like https://yande.re/post/similar?search_id=0a93a66d1126ee5be9ce09bee1328c5d.png&threshold=0&services=all&forcegray=1 )
